[package]
name = "zakura-halo2-legacy-pdqsort"
description = "A copy of the core::slice::sort module from the Rust 1.56.1 standard library, modified to behave the same on 32-bit platforms as on 64-bit, working around a determinism bug in the halo2_proofs crate"
keywords = ["sorting", "determinism", "halo2", "zcash"]
categories = ["algorithms"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "halo2_legacy_pdqsort"

[dev-dependencies]
rand = "0.10"
